### ISSUE TITLE
getCurrentContext deprecation

### ISSUE THREAD

**Issue by techwritescode** [ShoppinPal/multi-tenant-loopback-example#6]
Any ideas on a way around this: https://docs.strongloop.com/display/public/LB/Using+current+context

**Comment by pulkitsinghal** [comment]
There are extremely deep discussions on this topic and still no conclusion that everyone can agree on: https://github.com/strongloop/loopback/issues/1495

I prefer to use shrinkwrap from earlier working versions of loopback context with CLS and stay below v2.29.0

**Comment by pulkitsinghal** [comment]
@simonhochrein - thanks for closing this. i hope you found some form of closure 👍
